= Building a Microservice

In this section, students will build a new micro service ready for deployment to Pivotal CF.

== Microservice Architectures

*NOTE*: To get the Keynotes, clone/fork the repo or "Save As".

* Review the presentation on link:ArchForCDMicroservices.key[Pivotal CF and Microservices]

* Review the documentation on link:http://docs.pivotal.io/pivotalcf/devguide/deploy-apps/prepare-to-deploy.html[Considerations for Designing and Running an Application in the Cloud]

* Review the documentation on link:http://docs.pivotal.io/pivotalcf/devguide/deploy-apps/streaming-logs.html#writing[Writing to logs]

== Exercise

Build a functional micro service that can be deployed to Pivotal CF.

* The service must return data in JSON format.
* Data can be hardcoded at this stage, however in upcoming exercises a mysql database will be injected and bound.  Plan accordingly.
* All received requests should be logged.  We will use these logs in an upcoming exercise.

Java/Spring developers should follow the link:java-spring-microservice.adoc[script].
