= Pivotal CF Associate Training

== Instructor TO DO

. Set up windows VMs w/ vCenter for each env

. Github organization

== Notes & Goals

* Work in progress.

* The goal is not to re-invent content but to leverage existing sources and refine to ensure a cohesive evolution of understanding while building a comprehensive, functional solution.

* Scope will be refined based on what we believe a developer can achieve.  Detailed scope is defined in each sub model.  Timing is the critical factor in finalizing this.

* Exercises and slide content will be aggregated from existing sources and revised as needed.

* Slide content is anticipated to be minimal.  Whenever possible maintained docs should be referenced (i.e. from docs.pivotal.io).  Our docs site + team are incredible and content is up to date.  Syncing into a different format (i.e. slides) will not benefit an SI.  We want to get them used to referencing the docs site and we want to alleviate ourselves from the burden of syncing content.

* Dependencies exist on the environment in use and will have an impact on scoping.

== General Approach

This is an overview only.  See each sub model for scoping details & complete success criteria.  The goal is to create a flow that builds conceptually and functionally throughout the duration of the course.

At the end of the 4 day course, the student should have a custom built micro service that meets the following:

* Auto scaled
* Monitored
* Has its logs aggregated and dumped into an external logging analysis tool (i.e. splunk)
* Flows through the API Gateway
* Secured via an app security group
* The micro service will leverage a custom created service and service broker.  The broker will be deployed to PCF.
* The application will be fully automated for full continuous delivery using the blue/green deployment approach.
* Remotely debuggable through an IDE
* Run using a customized build pack
* Is deployed on a student installed PCF installation on vCloud Air which is fully monitored

The environment will dictate if we can include requirements on operational demonstrations (deployed PCF, Syslog draining, Ops metrics, etc).

== Prerequisites

=== Pivotal Academy

Students will have completed the following courses on Pivotal Academy:

* link:https://pivotalpartners.biglms.com/courses/Partners/Pivotal100/VWN/about[Pivotal100]: Introduction to Pivotal
* link:https://pivotalpartners.biglms.com/courses/PivotalU/CF200/VWZP/about[CF200]: Pivotal CF Getting Started

=== Developer Set Up

Students should have the following:

* Active Github account
* git client installed locally
* Their favorite IDE

== Associate Certification

=== Success Criteria

* Students will be allowed to pair during the class but each have to submit their own completed exercises.

* Students are expected to complete each module.

* All code will be pushed by students into a github repo for review and in case they need to continue working after the class to complete the tasks below.

=== Agenda

. link:kick-off/README.adoc[Kick Off]
** Introductions
** Session Expectations
** Pre-requisite Validation

. link:overview/README.adoc[Pivotal CF Overview]
** Intro to Pivotal CF
** Technical Overview
** Resources

. link:operations/README.adoc[Installation, Configuration and Management Basics]: Paired installation that will be used throughout the class
** Installing Pivotal CF
** Managing Products with Ops Manager
** Scaling the platform
** PaaS monitoring with Ops Metrics
** Syslog Draining
** Backing up Pivotal CF
** Bosh basics & troubleshooting

. link:dev-experience/README.adoc[Developer Experience - Part 1]
** The Command Line Interface
** Targeting
** Console basics
** Orgs, spaces, roles and permissions
** Quotas

. link:microservice/README.adoc[Building a Microservice]: Pair to create a simple micro service
** PaaS ready apps & best practices
** 12 factor apps

. link:dev-experience/README.adoc[Developer Experience - Part 2]: Use the micro service and perform the following actions/integrations:
** Pushing apps
** Using Manifests
** Dependency Injection in Spring
** Health, logging & events via the CLI
** Binding to services
** Environment variables
** Scaling apps
** IDE integration
** App log aggregation via a User Provided Service Instance
** Monitoring with APM tools
** Remote debugging
** Application Security Groups
** Application Autoscaling
** Continuous Delivery

. link:service-broker/README.adoc[Creating a Custom Service Broker]: Pair to create a custom service and bind it to your micro service.

. link:buildpack/README.adoc[Customizing Build Packs]: Customize a build pack and use it to deploy your micro service.

. link:api-gateway/README.adoc[API Gateway]: Transform the data from your micro service using the API gateway.

== Possible Topics

* Docker
* Push Notification
* Data Sync
* PHD Service
* Sizing PCF installations
* How do we incorporate domains?
