= Student Set Up

The following resources are required for the class.

== Git Client
This class requires you to have git client software installed.  If you don't already have git installed, we recommend the following:

=== Mac
Either of the following:

* GitHub graphical Git client, can download link:https://mac.github.com/[here].  Be sure to install the command line tools during the install.
* Git command line, can download link:http://git-scm.com/downloads[here].

=== Windows
 * git for windows, can download link:https://msysgit.github.io/[here].  During the install, select the option for bash shell only.  Then run the Git Bash application from the Start Menu rather than the Git GUI application.  We've found that this approach eliminates a lot of problems for students with windows laptops.

You should be familar with the git command line basics:

* git clone - clone an existing repo
* git add - add new or existing file to index to be committed
* git commit -m "commit message" - record changes to the repo
* git push - push committed changes to the remote repo
* git status - show status of local changes

== Class Repositories

=== PCF Immersion Repository

Clone this repository so that you have access to the presentations.
PDF copies are included in the same directory as each Keynote.

[source,bash]
----
$ git clone <this-repo>
----


=== Exercise Repository: pcf-immersion-workspace

A repository has been set up for individual class exercises.  You will need to fork link:https://github.com/pcf-alliances-immersion/pcf-immersion-workspace[this repository] and make it public in your github account.  Do not rename the repository and be sure you *commit all of your work to your fork*.

==== Updating the pcf-immersion-workspace

If you need to pull in changes to the workspace repository, you need to fetch the upstream changes and merge them.  From your fork:

* Display your current fork:
+
[source,bash]
----
$ git remote -v
----
+

* Add the upstream remote:
+
[source,bash]
----
$ git remote add upstream https://github.com/pcf-alliances-immersion/pcf-immersion-workspace.git
----
+

* Verify you now have an upstream:
+
[source,bash]
----
$ git remote -v
----
+

* Now fetch upstream changes:
+
[source,bash]
----
$ git fetch upstream
----
+

* Merge the changes:
+
[source,bash]
----
$ git merge upstream/master
----
+

* You now have the changes.  Be sure to commit and push at some point.


== Student VM

A student VM is provided which includes all the tools needed for the class.  Use of this VM is optional.

=== VM Details

The VM is Ubuntu 14.04.1.  It contains:

* Cloud Foundry CLI
* Ruby
* Bundler
* Bosh CLI
* Git
* Java
* Gradle
* Spring Source Tool Suite
* Remmina (Remote Desktop Client)
* JMeter

The packer scripts used to build the box are included in this repository in the `packer` directory in case you would like to make changes to the box.

=== Using the box

The student VM is distributed as a vagrant box.  Be sure you have Vagrant and the Virtual Box provider installed.

==== Adding the box

The box will be distributed via thumb drive.

. Copy the .box file to your local machine.

. Add the box to vagrant:
+
[source,bash]
----
$ vagrant box add pcf-immersion-box <PATH_TO_THE_BOX_FILE>
----
+


==== Launching the VM

A Vagrantfile is included in the `pcf-immersion-workspace` project.

To launch the box:

[source,bash]
----
$ cd pcf-immersion-workspace
$ vagrant up
----


==== Logging into the box

* The vm will launch with a UI.  However, unless you are using Remote Desktop or STS, you don't need to be logged into the UI.  Instead you can simply ssh.  From your `pcf-immersion-workspace` directory:
+
[source,bash]
----
$ vagrant ssh
----

* If you can't find the installed software on the path, you may need to explicitly load the profile:
+
[source,bash]
----
$ source ~/.bash_profile
----


* To login to the UI, use the default username/password which is vagrant/vagrant.  To open a new terminal window, use the shortcut ctrl+alt+t (control+option+t for mac), then source the bash profile as shown above.

==== Sharing a directory

By default, vagrant will share the project directory containing the Vagrantfile and sync it between your machine and the VM.  In the VM, the share is be default located at `/vagrant`.

*It is HIGHLY recommended that you use this directory for classwork.*

This will prevent you from losing your work in the event you run a `vagrant destroy` or otherwise harm the VM.

Note: You should also be committing and pushing to your fork frequently.

==== Cutting & Pasting

By default, VirtualBox disables cutting and pasting between your host and the VM.  To enable it:

. Be sure the VM is running
. VirtualBox > Settings > General > Advanced > Shared Clipboard (Bidirectional)
. Restart the VM:
+
[source,bash]
----
$ vagrant halt
$ vagrant up
----
+
