= Continuous Delivery

== Goals

This lab will guide you through building a BASIC continuous delivery pipeline using Jenkins, Artifactory, and Cloud Foundry.

== Exercise

*NOTE*: To get the Keynotes, clone/fork the repo or "Save As".

. Review the link:EnablingContinuousDelivery.key[Enabling Continuous Delivery] presentation

=== Set Up

We will leverage the Jenkins instance deployed by Ops Manager.  This is located at https://pivotal-cloudbees.run.pcf.jkruckcloud.com

This section of the course relies on you having a github account. If you don't have one, it's time that you do. link:http://github.com

Fork this repo: link:https://github.com/krujos/hello-java

=== Create the Initial Build Job

. Click `new item`, give it a name and select `maven project` Then click `OK`.

. Under `Source Code Management`, select `Git`, and supply your repository URL

. Under `Build Triggers`, select `Build when a change is pushed to GitHub`

. Add a post build step which pushes to your development space. 

.. It's an "execute shell" type of step

.. the shell script is up to you, but it should be as simple as Install the CLI, login, push

```
wget -N http://go-cli.s3-website-us-east-1.amazonaws.com/releases/latest/cf-linux-amd64.tgz
tar -zxvf cf-linux-amd64.tgz
./cf login -a -u -p -s -o --skip-ssl-validation`
./cf push --random-route
```

=== Github Set Up

. Go to https://github.com/<YOUR ACCOUNT>/hello-java > Settings > Webhooks & Services > Services > Add a Service > Jenkins (Github plugin)

. Jenkins hook url: https://pivotal-cloudbees.run.pcf.jkruckcloud.com/github-webhook/

+
* Make sure you include the trailing slash. The integration between github and jenkins will not work without it.
+

. Be sure `Active` is checked and click `Add Service`

=== Do the needful 

. Make a change

.. Editing the README or the Code in the web editor will do the trick, toggle back over to jenkins, watch for magic. 

. Did it work? 

.. You have now earned a release party. Notice the test trend graphic as well.


This is a good time (depending on where we're at in the class) to show what a "better" ci pipeline would look like with a demo of something real. 


== Beyond the Class

The CD exercise above is very simplistic and should be expanded for real projects.

=== Artifact Repository

Ideally, you want to build your artifacts (jars/wars) and publish them to a repository like Artifactory.

* Artifacts should be versioned to match the app deployments on PCF.
* All pushes to PCF should be using the same artifacts.  Artifacts should be built once and used throughout the lifecycle.

=== Code promotion

* Jobs should be established in Jenkins to deploy/promote code to different phases like dev to test to prod.
* Jobs should use the same artifact published to Artifactory.
* Jobs can be triggered automatically or manually but should be fully automated.  There should be no manual steps beyond clicking "build now".

=== Notification

Jenkins supports many notification plugins.  It is important for code owners to be aware of build status.
