= Continuous Delivery

== Goals

This lab will guide you through building a BASIC continuous delivery pipeline using Jenkins, Artifactory, and Cloud Foundry.

== Exercise

. Review the link:EnablingContinuousDelivery.key.zip[Enabling Continuous Delivery] presentation

=== Set Up

==== Jenkins Setup Steps

We will leverage the Jenkins instance deployed by Ops Manager.  This is located at https://pivotal-cloudbees.<YOUR SYSTEM DOMAIN>

. Login to your Jenkins instance deployed by Ops Manager.  Use the `Admin` user under `UAA`.

. Navigate to `Manage Jenkins` > `Configure System`

. Add the JDK 1.8 installation under the `JDK` section
+
* `Add Installer` > `Install from java.sun.com`
* Agree to the license
* Provide your Oracle login information
* Ensure `Install automatically` is selected
+

. Add the latest stable Gradle under the `Gradle section`
+
* Ensure `Install automatically` is selected
* `Install from Gradle.org`

. Click `Apply` then `Save`

. Navigate to `Manage Jenkins` > `Manage Plugins` > `Available`

. Ensure the following plugins are installed:
+
* Gradle (should be installed)
* Mask Passwords
* Extensible Choice Parameter Plugin
* Artifactory Plugin
* Parameterized Remote Trigger Plugin
+

. Tell Jenkins to restart after plugin install

=== Create the Initial Build Job

. Navigate back to Jenkins Home.

. Click `create new jobs`, give it a name and select `Build a free-style software project` Then click `OK`.

. Under `Source Code Management`, select `Git`, and supply your repository URL and credentials

. Under `Build Triggers`, select `Poll SCM` and provide the string `* * * * *` (every minute).

. Under `Build`, add a `Invoke Gradle Script` build step.
+
Gradle Version:: The one you created above
Build Step Description:: +build environment agnostic artifact+
Switches:: `-Pbuildversion=$BUILD_NUMBER`
Tasks:: `clean assemble`

. Save the config and try running the build by clicking ``Build Now''.

=== Configure the CF Deployments

. From the job config, select `This build is parameterized` and enter the following `String values` with appropriate defaults:
+
* CF_DOMAIN: the CF system domain
* CF_USER: the user account
* CF_PWD: your password
* CF_ORG: org to deploy to
* CF_SPACE: space to deply to
* CF_APP: the app name
* CF_JAR: path to the jar on jenkins
* CF_MANIFEST: path to the manifest on jenkins
+

. You can find the values for CF_JAR and CF_MANIFEST by clicking on `Workspace` in the job config

. Select `Add build step` > `Execute Shell`.  Paste the following:
+
[source,bash]
----

#!/bin/sh

wget http://go-cli.s3-website-us-east-1.amazonaws.com/releases/latest/cf-linux-amd64.tgz
tar -zxvf cf-linux-amd64.tgz
./cf --version
./cf login -a https://api.$CF_DOMAIN -u $CF_USER -p $CF_PWD -o $CF_ORG -s $CF_SPACE --skip-ssl-validation

DEPLOYED_VERSION_CMD=$(CF_COLOR=false ./cf apps | grep $CF_APP- | cut -d" " -f1)
DEPLOYED_VERSION="$DEPLOYED_VERSION_CMD"
ROUTE_VERSION=$(echo "${BUILD_NUMBER}" | cut -d"." -f1-3 | tr '.' '-')
echo "Deployed Version: $DEPLOYED_VERSION"
echo "Route Version: $ROUTE_VERSION"

./cf push "$CF_APP-$BUILD_NUMBER" -n "$CF_APP-$ROUTE_VERSION" -d $CF_DOMAIN -p $CF_JAR -f $CF_MANIFEST
./cf map-route "$CF_APP-${BUILD_NUMBER}" $CF_DOMAIN -n $CF_APP
./cf scale "$CF_APP-${BUILD_NUMBER}" -i 2

if [ ! -z "$DEPLOYED_VERSION" -a "$DEPLOYED_VERSION" != " " -a "$DEPLOYED_VERSION" != "$CF_APP-${BUILD_NUMBER}" ]; then
  echo "Performing zero-downtime cutover to $BUILD_NUMBER"
  echo "$DEPLOYED_VERSION" | while read line
  do
    if [ ! -z "$line" -a "$line" != " " -a "$line" != "$CF_APP-${BUILD_NUMBER}" ]; then
      echo "Scaling down, unmapping and removing $line"
      ./cf scale "$line" -i 1
      ./cf unmap-route "$line" $CF_DOMAIN -n $CF_APP
      ./cf delete "$line" -f
    else
      echo "Skipping $line"
    fi
  done
fi
----

. Click `Save` and run your build

. Commit a change to git and watch the magic
