= Continuous Delivery

== Goals

This lab will guide you through building a BASIC continuous delivery pipeline using Jenkins, Artifactory, and Cloud Foundry.

== Exercise

*NOTE*: To get the Keynotes, clone/fork the repo or "Save As".

. Review the link:EnablingContinuousDelivery.key[Enabling Continuous Delivery] presentation

=== Set Up

==== Jenkins Setup Steps

We will leverage the Jenkins instance deployed by Ops Manager.  This is located at https://pivotal-cloudbees.<YOUR SYSTEM DOMAIN>

. Login to your Jenkins instance deployed by Ops Manager.  Use the `Admin` user under `UAA`.

. Navigate to `Manage Jenkins` > `Configure System`

. Add the JDK 1.8 installation under the `JDK` section
+
* `Add Installer` > `Install from java.sun.com`
* Agree to the license
* Provide your Oracle login information
* Ensure `Install automatically` is selected
+

. Add the latest stable Gradle under the `Gradle section`
+
* Ensure `Install automatically` is selected
* `Install from Gradle.org`

. Click `Apply` then `Save`

. Navigate to `Manage Jenkins` > `Manage Plugins` > `Available`

. Ensure the following plugins are installed:
+
* Gradle (should be installed)
* Mask Passwords
* Extensible Choice Parameter Plugin
* Parameterized Remote Trigger Plugin
* Github Plugin
+

. Tell Jenkins to restart after plugin install

=== Create the Initial Build Job

. Navigate back to Jenkins Home.

. Click `create new jobs`, give it a name and select `Build a free-style software project` Then click `OK`.

. Under `Source Code Management`, select `Git`, and supply your repository URL and credentials

. Under `Build Triggers`, select `Build when a change is pushed to GitHub`

. Under `Build`, add a `Invoke Gradle Script` build step.
+
Gradle Version:: The one you created above
Build Step Description:: +build environment agnostic artifact+
Switches:: `-Pbuildversion=$BUILD_NUMBER`
Tasks:: `clean assemble`
Root Build Script:: This should be something like: `cities/cities-service`.  You can verify by manually triggering a build then viewing the 'Workspace' link.

. Save the config and try running the build by clicking ``Build Now''.

=== Configure the CF Deployments

. From the job config, select `This build is parameterized` and enter the following `String values` with appropriate defaults:
+
* CF_DOMAIN: the CF system domain
* CF_USER: the user account
* CF_ORG: org to deploy to
* CF_SPACE: space to deply to
* CF_APP: the app name
* CF_JAR: path to the jar on jenkins
* CF_MANIFEST: path to the manifest on jenkins
+

. Create a `Password Paramter` for:
+
* CF_PWD: your password
+


=== Github Set Up

. Go to https://github.com/<YOUR ACCOUNT>/pcf-immersion-workspace > Settings > Webhooks & Services > Services > Add a Service > Jenkins (Github plugin)

. Jenkins hook url: https://pivotal-cloudbees.<YOUR PCF SYSTEM DOMAIN>/github-webhook/

. Be sure `Active` is checked and click `Add Service`

. You can find the values for CF_JAR and CF_MANIFEST by clicking on `Workspace` in the job config

=== Configuring your Green/Blue deploy

. Back to the Jenkins job config...

. Select `Add build step` > `Execute Shell`.  Add the following and edit to ensure a blue-green deployment:
+
[source,bash]
----

cf login -a https://api.$CF_DOMAIN <Add the correct flags to include the username, password, org and space> --skip-ssl-validation

DEPLOYED_VERSION_CMD=$(CF_COLOR=false cf apps | grep $CF_APP- | cut -d" " -f1)
DEPLOYED_VERSION="$DEPLOYED_VERSION_CMD"
ROUTE_VERSION=$(echo "${BUILD_NUMBER}" | cut -d"." -f1-3 | tr '.' '-')
echo "Deployed Version: $DEPLOYED_VERSION"
echo "Route Version: $ROUTE_VERSION"

# push a new version and map the route
cf <???> "$CF_APP-$BUILD_NUMBER" -n "$CF_APP-$ROUTE_VERSION" -d $CF_DOMAIN -p $CF_JAR -f $CF_MANIFEST
cf <???> "$CF_APP-${BUILD_NUMBER}" $CF_DOMAIN -n $CF_APP

if [ ! -z "$DEPLOYED_VERSION" -a "$DEPLOYED_VERSION" != " " -a "$DEPLOYED_VERSION" != "$CF_APP-${BUILD_NUMBER}" ]; then
  echo "Performing zero-downtime cutover to $BUILD_NUMBER"
  echo "$DEPLOYED_VERSION" | while read line
  do
    if [ ! -z "$line" -a "$line" != " " -a "$line" != "$CF_APP-${BUILD_NUMBER}" ]; then
      echo "Scaling down, unmapping and removing $line"
      # Unmap the route and delete
      cf <???>-route "$line" $CF_DOMAIN -n $CF_APP
      cf <???> "$line" -f
      cf delete-route $CF_DOMAIN -n "$line" -f 
    else
      echo "Skipping $line"
    fi
  done
fi
----

. Click `Save` and run your build

. Commit a change to git and watch the magic


== Beyond the Class

The CD exercise above is very simplistic and should be expanded for real projects.

=== Artifact Repository

Ideally, you want to build your artifacts (jars/wars) and publish them to a repository like Artifactory.

* Artifacts should be versioned to match the app deployments on PCF.
* All pushes to PCF should be using the same artifacts.  Artifacts should be built once and used throughout the lifecycle.

=== Code promotion

* Jobs should be established in Jenkins to deploy/promote code to different phases like dev to test to prod.
* Jobs should use the same artifact published to Artifactory.
* Jobs can be triggered automatically or manually but should be fully automated.  There should be no manual steps beyond clicking "build now".

=== Notification

Jenkins supports many notification plugins.  It is important for code owners to be aware of build status.
