= Buildpacks

== Goal

In this section, students will deploy a build pack and use it to deploy an application.

== Obtain the modified buildpack_path
. You need to be logged in as admin for these exercises. 

* Download the buildpack from S3 to your laptop.
** https://s3-us-west-1.amazonaws.com/pcf-icm/java-buildpack-staging-timestamp.zip

. This buildpack has an added *framework* component that will set a Java system property containing a timestamp that indicates when the application was staged. 

* Upload our extended Java buildpack to Cloud Foundry. We'll leverage the cf CLI. Ensure that you're logged in to your CF instance as an admin user.
+
To add our buildpack, we'll leverage +cf create-buildpack+. Run that with zero command-line options to see how the command works:
+
[source,bash]
----
$ cf create-buildpack ...
----
+
* Be sure to name your buildpack <first-initial><last-name>-java-buildpack when executing the `cf create-buildpack` command.


=== Verifying your changes

. Now it's time to test our changes. The `cities-service` contains a very basic REST controller that returns the staging timestamp in response to a GET request.

. Access the `/staging` endpoint.  You should see a null timestamp as you aren't yet using your new build pack:
+
[source,bash]
----
$ curl -i http://<cities-service>/staging
HTTP/1.1 200 OK
Content-Length: 52
Content-Type: text/plain;charset=ISO-8859-1
Date: Tue, 27 May 2014 17:23:57 GMT
Server: Apache-Coyote/1.1
X-Application-Context: cities:cloud:0

Application was staged at: null
----
+

. Now, re-push your app and use the `-b` flag to use your modified build pack.

. Check the staging info provided by the Java build pack to see that our change was effective:
+
[source,bash]
----
$ cf files <cities-service> staging_info.yml

---
buildpack_path: /var/vcap/data/dea_next/admin_buildpacks/16b81d79-2a6a-426a-8cff-6daf779eadad_93ad9995be0bd22935c4590c6986061bbb0e9c0d
detected_buildpack: java-buildpack=158e5a6-https://github.com/cloudfoundry/java-buildpack.git#158e5a6
  java-main open-jdk-jre=1.7.0_55 spring-auto-reconfiguration=1.2.0_RELEASE staging-timestamp
start_command: SERVER_PORT=$PORT $PWD/.java-buildpack/open_jdk_jre/bin/java -cp $PWD/.:$PWD/.java-buildpack/spring_auto_reconfiguration/spring_auto_reconfiguration-1.2.0_RELEASE.jar
  -Djava.io.tmpdir=$TMPDIR -XX:OnOutOfMemoryError=$PWD/.java-buildpack/open_jdk_jre/bin/killjava.sh
  -Xmx382293K -Xms382293K -XX:MaxPermSize=64M -XX:PermSize=64M -Xss995K -Dstaging.timestamp='2014-05-27
  15:52:41 +0000' org.springframework.boot.loader.JarLauncher
----
+
As you can see from the output, our timestamp was added as the final +-D+ argument in the +start_command+.

. Access your application again from your browser and access the `/staging` endpoint.  You should now see a message that contains the timestamp:
+
[source,bash]
----
$ curl -i http://<cities-service>/staging
HTTP/1.1 200 OK
Content-Length: 52
Content-Type: text/plain;charset=ISO-8859-1
Date: Tue, 27 May 2014 17:23:57 GMT
Server: Apache-Coyote/1.1
X-Application-Context: cities:cloud:0

Application was staged at: 2014-05-27 15:52:41 +0000
----
+

. Edit your manifest to ensure future pushes leverage your build pack.
