= Instructor Notes


== Pace

Pace can vary from class to class.  However, we loosely try to get through according to the following pace.  Even if the class isn't ready, you may need to introduce the next topic for faster moving students and to hit all exercises in the allotted time.


=== Monday

Monday often feels rushed, but it is critical that everyone gets a PCF install w/ services kicked off before leaving for the day.  The installs can take a long time and we need to be able to verify everything was successful before class begins Tuesday morning.

* *Start*: 1PM start time to allow for travel

* *Introductions*:  Keep it brief. Name, company, background, experience with PCF, etc.

* *Session Expectations*: This is an accreditation course.  The expectation is that each student completes 100% of the exercises.  Communicate this clearly now.  No surprise failures!

* *Course structure & Student set up*: Introduce the main repositories.  Be sure every student understands how to navigate the exercise, presentations and course links.  Have each student clone the course repository and fork the workspace into their personal github account, then clone it locally.  Be sure they understand how to push changes to their workspace fork.  Now is the time to identify true git novices.

* *Intro to PCF*: Setting the stage for why Pivotal and why CF is extremely important.  Much of this material is included in the pre-reqs, but I believe it is important for each instructor to "nail" this portion, clearly communicating why this whole 3rd platform movement is happening and the impact it is having on customers.  This sets the stage for the class.

* *Technical Overview*: This presentation provides a high level overview of the components of PCF that will be used throughout the class.  Provide a solid foundation so that students know what is coming ("you are going to deploy a custom buildpack/broker") and so they have context at a high level as to what is happening behind the scenes.

* *Installing PCF and Products*: We have to rush to get here, but everyone MUST have an install running when they leave.  You can go into detail on Tuesday morning with regards to what they did and what happened during the install.


=== Monday Night

It is critical that the instructor(s) verify all of the PCF installations are successful and contain the necessary services.  We do not have time to re-install during the class.  If there are issues, note them and correct.  You can communicate the errors to the students on Tuesday.


=== Tuesday

The goal is to get through the entire operator experience.


=== Wednesday

Shift gears to the Developer Experience.  The goal is to up to (not through) the Continuous Delivery exercise.


=== Thursday

The goal is to introduce the remaining topics in the developer experience: Continuous delivery, buildpacks, and service broker.  Ideally, students can finish today.


=== Friday

Friday is all about bringing it altogether and feedback.  Depending on the general pace of the class, I might give students an hour or so before kicking off the summary exercise.


==== Summary Exercise

I do the summary exercises on the white board.  This has been extremely important and well received and I highly recommend you practice this ahead of time.

The goal is to guide students through everything that happened during the class to draw a series of pictures.  You are the facilitator, not the instructor.  The goal is to get students to think and direct your drawings.

===== Pic 1: vSphere

* Draw a box and label it vSphere.  The goal is to draw what was deployed during class.

* Add details like: Datacenter, Cluster, network, etc.


===== Pic 2: vSphere, the ideal

* Availability Zones: Define and discuss availability zones.  Be sure students are aware of the best practices.

* Networks: Define and discuss how PCF was deployed and the best practices to segment traffic.

===== Pic 3: PCF Install

* Draw the IaaS

* Layer PCF on top w/ bosh.  Be sure to draw the CPI

* Be sure to explain what Ops Mgr is, what each tile is, and what goes into a bosh release.

* Add Services.  Include brokers, and UPSI in the class.  Discuss the options.
