= Managing Products through Ops Manager

== Goal

To understand how to use Ops Manager to install and configure products and services.

== Exercise

In this exercise, you will install and configure the products which will be used in during the duration of the class.

=== Notes

* The jump box has a folder with the necessary products.
* It is recommended you access Ops Manager from the Jump Box in order to reduce network latency and upload times.

=== Installing Products

. Log in to your Ops Manager instance

. link:http://docs.pivotal.io/pivotalcf/customizing/pcf-interface.html[Familiarize] yourself with the interface.

. Review the documentation on link:http://docs.pivotal.io/pivotalcf/customizing/add-delete.html[Adding and Deleting Products]

. Install and configure the following:
+
* Elastic Runtime
* Mysql
* Autoscaling
* Jenkins
* Ops Metrics
+

. *Elastic Runtime*:
+
** HA Proxy Tab: Be sure to click the `Generate Self-Signed RSA certificate` link. Then, select `Trust Self-Signed Certificates`.
+
** Resource Sizes:
*** Increase the number of DEAs to 2.
*** Reduce the persistent disk size of the NFS Server to 51,200MB
*** Reduce the persistent disk size of the MySQL Server to 30,000MB
*** Ensure the Collector instance count is set to 1

. *Jenkins*: You will have to enter license information.  Enter your information to generate a temporary license.

. *Ops Metrics*: We will configure Ops Metrics in a later exercise.  In order to install it, you need to set up a JMX Provider username and password.  The user/pwd to use is provided in the environment spreadshet.

. *MySQL*:
+
** Resource Sizes:
*** Reduce the number of instances to 1.
*** Reduce the persistent disk to 50,000MB
*** Reduce Proxy instances to 1
*** Reduce Broker instances to 1

. When you have completed configuration, select `Install` or `Apply Changes` in the Ops Manager interface.
