= Monitoring Pivotal CF

We will configure PaaS monitoring via JMX and drain PCF system logs into a 3rd party log analysis tool.


== Retrieving logs via Ops Manager

. In Ops Manager, select `Elastic Runtime` > `Status`

. Review the status information

. Request the logs for HA Proxy

. Download the logs from the `Logs` tab and commit them into your github repo in the `operations` directory.  Name this file `haproxy-logs-opsmgr.zip`


== Installation & Configuration

Configure Ops Metrics and Syslog draining before deploying changes in Ops Manager.


=== Ops Metrics

In this section, you will install and configure the Ops Metrics tile.

. Follow steps 8 thru 15 to install & configure Ops Metrics: http://docs.pivotal.io/pivotalcf/customizing/deploy-metrics.html

. Be sure you have set the Instance count of the Collector (under Elastic Runtime) to 1.

. DO NOT enable SSL in the Ops Metrics tile.  This step is optional and jvisualvm won't be able to connect.

+
* *BEFORE APPLYING CHANGES* configure Syslog Draining below.
+


=== Syslog Draining

. Sign up for a free Papertrail account: https://papertrailapp.com/

. *Follow steps 1-4 ONLY* on link:http://docs.run.pivotal.io/devguide/services/log-management-thirdparty-svc.html#papertrail[Setting up Papertrail]

. In Ops Manager and select `Elastic Runtime` > `External Endpoints`

. Enter the address and port displayed for your Papertrail system.  For `Networking Protocol` select TCP protocol.  Click `Save`.


=== Apply changes

. Before applying changes: Select `Lifecycle Errands` from the `Elastic Runtime` tile.  Uncheck all of the post install errands.  This will speed up the update by ensuring these errands are not re-run.

. From the Ops Manager dashboard, apply your changes.




== Monitoring


=== Monitoring with Java VisualVM

*To avoid adding a firewall mapping, we will connect to the Ops Metrics service from the JumpBox.*

Java VisualVM ships with the JDK.  It provides the ability to drill into MBeans, but does not provide graphical and time based analysis.

. Launch Java VisualVM from a terminal window on the JumpBox:
+
[source,bash]
----
$ jvisualvm
----

. We have already installed the MBeans tool for you (Select `Tools` > `Plugins` > `Available Plugins` > `VisualVM-MBeans` > `Install`)

. From the left side bar, select `Remote`

. Enter the IP of your Ops Metrics VM (available in Ops Manager).  Click `OK`.

. Right click the new Remote host and select `Add JMX Connection`.
+
. Set the port to 44444
. Check `Use Security Credentials` and enter the user/pwd you set up in the Ops Metrics tile
. Select `Save Security Credentials`
. Select `Do not require SSL connection`
. Click `Ok`
+

. In the left side bar, double click the new JMX remote endpoint and select the `MBeans` tab

. Metrics will be under `org.cloudfoundry`

. Be sure to save your configuration in jvisualvm


=== Using Papertrail

. When complete, open the Papertrail dashboard and look at the logs.


=== Beyond the class

==== Ops Metrics

. Review the documentation on Using Ops Metrics: http://docs.pivotal.io/pivotalcf/customizing/use-metrics.html

. Java VisualVM does not provide real time charts of MBeans.  Consider a more robust JMX solution like AppDynamics, NewRelic, Splunk, or Hyperic.

==== Splunk Enterprise

If you would like to use Splunk on your PCF instances, see link:http://docs.run.pivotal.io/devguide/services/integrate-splunk.html[Integrating Splunk] to install the correct log formatting tools for PCF.

==== Firehose

The first version of the link:https://groups.google.com/a/cloudfoundry.org/forum/#!msg/vcap-dev/FE_w5xDG-dg/EPoUMY_B3JkJ[firehose] was just released as part of cf-release (OSS).
