= Monitoring Pivotal CF

We will configure PaaS monitoring via JMX and drain PCF system logs into a 3rd party log analysis tool.


== Retrieving logs via Ops Manager

. In Ops Manager, select `Elastic Runtime` > `Status`

. Review the status information

. Request the logs for HA Proxy

. Download the logs from the `Logs` tab and commit them into your github repo.


== Installation & Configuration

Configure Ops Metrics and Syslog draining before deploying changes in Ops Manager.


=== Ops Metrics

In this section, you will install and configure the Ops Metrics tile.

. Follow steps 1 thru 7 to install & configure Ops Metrics: http://docs.pivotal.io/pivotalcf/customizing/deploy-metrics.html
+
* *BEFORE APPLYING CHANGES* configure Syslog Draining below.
+


=== Syslog Draining

. Sign up for a free Splunk Storm account: http://www.splunkstorm.com

. *Follow steps 1-5 ONLY* on link:http://docs.run.pivotal.io/devguide/services/log-management-thirdparty-svc.html#splunkstorm[Setting up Splunk Storm]
+
* For *Step 4*, the IP to authorize is provided by the instructors.  This is the IP of the externally facing firewall/NAT box for your installation.
+

. In Ops Manager and select `Elastic Runtime` > `External Endpoints`

. Enter the IP address and port displayed in your Splunk Storm project page and click `Save`

=== Apply changes

. Before applying changes: Select `Lifecycle Errands` from the `Elastic Runtime` tile.  Uncheck all of the post install errands.  This will speed up the update by ensuring these errands are not re-run.

. From the Ops Manager dashboard, apply your changes.


=== Updating Ops Manager Director and Elastic Runtime
. Configure Ops Manager Director's Metrics IP address and update the Elastic Runtime's Collector instance count: http://docs.pivotal.io/pivotalcf/customizing/deploy-metrics.html
* *NOTE*: Start at step 8 as you should have already installed Ops Metrics.


== Monitoring


=== Monitoring with Java VisualVM

*To avoid adding a firewall mapping, we will connect to the Ops Metrics service from the JumpBox.*

Java VisualVM ships with the JDK.  It provides the ability to drill into MBeans, but does not provide graphical and time based analysis.

. Launch Java VisualVM from a terminal window on the JumpBox:
+
[source,bash]
----
$ jvisualvm
----

. We have already installed the MBeans tool for you (Select `Tools` > `Plugins` > `Available Plugins` > `VisualVM-MBeans` > `Install`)

. From the left side bar, select `Remote`

. Enter the IP of your Ops Metrics VM (available in Ops Manager).  Click `OK`.

. Right click the new Remote host and select `Add JMX Connection`.
+
. Set the port to 44444
. Check `Use Security Credentials` and enter the user/pwd you set up in the Ops Metrics tile
. Select `Save Security Credentials`
. Select `Do not require SSL connection`
. Click `Ok`
+

. In the left side bar, double click the new JMX remote endpoint and select the `MBeans` tab

. Metrics will be under `org.cloudfoundry`

. Be sure to save your configuration in jvisualvm


=== Using Splunk Storm

. When complete, open the Splunk Storm project dashboard and look at the logs.


=== Beyond the class

==== Ops Metrics

. Review the documentation on Using Ops Metrics: http://docs.pivotal.io/pivotalcf/customizing/use-metrics.html

. Java VisualVM does not provide real time charts of MBeans.  Consider a more robust JMX solution like AppDynamics, NewRelic, Splunk, or Hyperic.

==== Splunk Enterprise

If you would like to use Splunk on your PCF instances, see link:http://docs.run.pivotal.io/devguide/services/integrate-splunk.html[Integrating Splunk] to install the correct log formatting tools for PCF.

==== Firehose

The first version of the link:https://groups.google.com/a/cloudfoundry.org/forum/#!msg/vcap-dev/FE_w5xDG-dg/EPoUMY_B3JkJ[firehose] was just released as part of cf-release (OSS).
