= Orgs, Spaces, Quotas, Users & Roles

== Overview

In this section, we will log in and create the necessary structures for the rest of the class.

== Exercises

=== The Command Line Interface (CLI)

. Review the documentation on the link:http://docs.pivotal.io/pivotalcf/devguide/installcf/whats-new-v6.html[Command Line Interface]

. Review the documentation on link:http://docs.pivotal.io/pivotalcf/customizing/api-endpoint.html[API Endpoints & Targeting]

. Target and log in to your Pivotal CF instance

=== Users, Orgs, Spaces, & Roles

. Review the documentation on link:http://docs.pivotal.io/pivotalcf/concepts/roles.html[Orgs, Spaces, Roles, and Permissions]

==== Orgs & Spaces

. Create a new organization: `first initial + last name` in all lower case.

. Create a new space in your org called `development`.

. Create a new space in your org called `qa`.

==== Users & Roles

. Create a new user account for yourself and assign the minimum role(s) required for you to manage applications and services.  Do this for both the development and qa spaces.

==== Quotas

. View the settings for the `default` quota.

. Create a new quota for your organization named `first initial + last name_org-quota`.  Allow up to 20GB of memory.  Use the same settings as the `default` quota for other inputs.  Assign the quota to your org.
+
* *DO NOT* follow the docs.pivotal.io guide as this is out of date.  You should be using the `cf` commands instead of curl requests.
+

. Create a new quota for your development space named `first initial + last name_dev-space-quota`.  Allow up to 10GB of memory.  Ensure an app instance can use up to 2GB of memory.  Use the same settings as the org for other inputs.  Assign the quota to your development space.
+
* *DO NOT* follow the docs.pivotal.io guide as this is out of date.  You should be using the `cf` commands instead of curl requests.
+
