= The Platform Operators Benevolence 

During this workshop your instructors (Josh and Duncan OR Chris) have assumed the role of Platform Operator. It's likely that at some point during the class we'll hand over the keys and have you operate the platform if you desire. Each student has been provided an organization that follows the naming pattern <first_initial><last_initial>-org. So Josh's would be `jk-org`. 

An organization is the unit of tenancy in Cloud Foundry. Within your org you'll find two spaces. The development space is meant as a safe place for experimentation. The production space is intended for live apps serving customers. Of course your actual deployment may have more spaces. These are configurable per Tennant and generally the tenant's concern and management responsibility. We've preconfigured spaces and orgs for you to illustrate some platform features. This will become evident further on `<evil laugh>`. 

You've also been provided a user account. Please login to the platform using your Home Depot email address (all lower case) and the password 'password'. Follow the prompts, and select the 'production' space. 

We'll discuss a few things here: 

. Orgs

. Spaces

. Quotas

. Users and their scope

. Application security groups
We will cover these briefly and *experience* them later.

== Additional Reading

. link:http://docs.pivotal.io/pivotalcf/concepts/roles.html[Orgs, Spaces, Roles, and Permissions]

. link:http://docs.pivotal.io/pivotalcf/adminguide/app-sec-groups.html[Application Security Groups]

