
= Monitoring with APM tools

== Goal

To understand the APM monitoring options and enable APM monitoring

== Exercise

. Review the Java buildpack documentation on:
+
* link:https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-app_dynamics_agent.md[AppDynamics]
* link:https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-new_relic_agent.md#configuration[New Relic]
* link:https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-spring_insight.md[Spring Insight]

. Sign up for a free link:http://appdynamics.com[AppDynamics] account

. Create a user provided service instance and bind it to your cities-ui application. link:http://www.appdynamics.com/blog/java/monitoring-apps-on-the-cloud-foundry-paas/[Reference]

. Make sure you're using your **production** instance!

+
[source,bash]
----
$ cf cups app-dynamics -p host-name,port,ssl-enabled,account-name,account-access-key
----

. Enter the requested info.  This is displayed under the `Account Info` section on your App Dynamics account page.
+
* *For the `ssl-enabled` parameter, be sure to enter `true`.*
* *Hostname is actually a hostname, make sure you don't have `http`!*
+

. Bind the new instance to your application and restart.

. Launch the AppDynamics console and execute curl requests against your application.

. Note you can also try binding to your cities-service application. This will cause some interesting errors to take a look at and what CF does and logs because of them.

Note:  If you see permgen errors in the log, treat them as general out of memory errors.  You don't need to hack the java buildpack as part of this exercise.


== Checking your work

. Your App Dynamics service should show correctly under the VCAP_SERVICES environment variable. After a bit you should see data in the app dynamics console as well.

. Time permitting this is a fun place to fool around for a bit. See what kind of errors you can cause for your app and how that manifests itself in your monitoring tool. This is your first line of defense, is the monitoring tools cluing you into to things that you could use CF to fix (response times, service errors)?


+
[source,bash]
----
$ cf env <first-inital><last-initial>-cities-service
----

. QUESTION / Class Exercise: This should work from production, but not from development. Can you analyze the security groups for each space and explain why? What security group applies to the production space?
