= IDE Integration

In this exercise, you will enable the Cloud Foundry plugins in your IDE.

== STS/Eclipse Integration

=== Installing the Plugin

*NOTE:*  We have recently seen problems with newer versions of the plugin not being able to connect to non-trusted URLs like the one we use in this class.  If you experience this problem, please
try installing an older version of the plugin via the "Install a Release Version Offline" section in the first link below.  We've had success with the 1.7.3 version of the plugin.


. Follow the plugin installation guide: http://docs.pivotal.io/pivotalcf/buildpacks/java/sts.html#install

. Review the Interface documentation: http://docs.pivotal.io/pivotalcf/buildpacks/java/sts.html#plugin-ui

=== Create a Cloud Foundry Server

. Review the documentation on creating CF Servers: http://docs.pivotal.io/pivotalcf/buildpacks/java/sts.html#cloud-foundry-server

. Create a server pointing to the PCF installation, Organization, and Space you have deployed your microservice too.

. Be sure to use the `Validate Account` feature to ensure you have configured your credentials correctly.

=== Deploy your Microservice

. Review the documentation on deploying applications: http://docs.pivotal.io/pivotalcf/buildpacks/java/sts.html#deploy-an-application

. You will need to CTRL-Click on your app, select `Configure` then `Enable as a Cloud Foundry App`

. Use the plugin to remove and then re-deploy your microservice

. NOTE: This version of the plugin has an issue parsing manifests and you will need to provide inputs to STS.  It is not recommended to have Eclipse generate/save changes to your manifest.

=== Further Reading

Plugin features are documented here: http://docs.pivotal.io/pivotalcf/buildpacks/java/sts.html.
