= Running the Spring Boot Microservice Locally

In this exercise, you will setup the `cities` microservice and run it locally.

== Set Up

=== Fork the repository

* Fork the `pcf-immersion-workspace` project into your own public repository.  This repository must be public for the instructors to review it.

=== Import into STS

From your `pcf-immersion-workspace` fork:

* To prepare the project for STS/Eclipse: change to the `cities/cities-service` directory and run
+
[source,bash]
----
$ gradle eclipse
----
+
* Open STS and select: `File` > `Import` > `Gradle` > `Gradle Project`
* Select the `cities-service` directory
* Click `Build Model`, select the project and click `Finish`

== Deploying

=== Running the application locally with Spring Boot

. Build the application:
+
[source,bash]
----
$ gradle assemble
----

. Run the application locally to be sure it works:
+
[source,bash]
----
$ java -jar build/libs/cities-service-0.0.1-SNAPSHOT.jar
----

. Access the application using `curl`
+
[source,bash]
----
$ curl -i http://localhost:8080
----
+
You'll see that the primary endpoint automatically exposes the ability to page, size, and sort the response JSON.

. `curl` for results
+
[source,bash]
----
$ curl -i http://localhost:8080/cities
----
+
You'll see that we have already loaded a large data set upon startup.  The application is currently using an in memory hypersonic database. We will change this to use an external mysql database soon.

. Try the following +curl+ statements to see how the application behaves:
+
[source,bash]
----
$ curl -i localhost:8080/cities?size=5
$ curl -i localhost:8080/cities?size=5&page=3
$ curl -i localhost:8080/cities?sort=postalCode,desc
----

=== FYI: Using Spring Boot Actuator

Try out the following endpoints. The output is omitted here because it can be quite large:

http://localhost:8080/beans:: Dumps all of the beans in the Spring context.
http://localhost:8080/autoconfig:: Dumps all of the auto-configuration performed as part of application bootstrapping.
http://localhost:8080/env:: Dumps the application's shell environment as well as all Java system properties.
http://localhost:8080/metrics:: Dumps all metrics currently being collected by Actuator, primarily response time and access counts for endpoints.
http://localhost:8080/mappings:: Dumps all URI request mappings and the controller methods to which they are mapped.

=== Shutdown

. Shutdown the application
