= Developer Experience

== Goals

To deploy and configure an application, leverage the platform for monitoring & management of the microservices, and automate a continuous delivery pipeline.

== Exercises

=== Console

Before we do anything lets take a look at the developer console and confirm install of the Cloud Foundry CLI on our laptops/desktops. 

* link:http://docs.pivotal.io/pivotalcf/console/dev-console.html[User Console Docs]

* login to the console at https://console.run-at.homedepot.com
* Your laptop should already trust the THD RootCA, if it dosen't proceed anyway. 
* If you're using chrome, make sure it's a recent. Folks from THD have had some issues with an older version 
* Login with your THD email (all lowercase) and a password of `password`
* Navigate to "Tools" (Left side)
* Download and install the CLI for your platform..

=== CLI
Now that we have the CLI, lets push some basic applications quickly and navigate our way around the CLI. 

* Login to Cloud Foundry

`cf login -a https://api.run-at.homedepot.com -u <your email> -p password -o <your org> -s development` 

.. Note if you had SSL errors above, you can add `--skip-ssl-validation` to the command.

. `-a` is the api we're targeting. Meaning all actions we perform will take place on this Cloud Foundry Foundation (deployment)

. `-u` is your username, in this workshop it's your email address.

. `-p` is your password. I've set it to `password`

. `-o` is the name of your organization

. `-s` is the name of your space

. `--skip-ssl-validation` lets the CLI use a self signed cert (or a cert where the names don't match up).

=== Pushing apps
* **Make sure you're logged into your development space (run `cf target` to check)**

* Clone our example applications

`git clone https://github.com/krujos/cf-hello-world-sample-apps`

`cd cf-hello-world-sample-apps`

* No git? link:https://s3-us-west-1.amazonaws.com/pcf-icm/demo-apps.zip[No problem, download the apps here.]

Read link:https://github.com/krujos/cf-hello-world-sample-apps/blob/pro/README.md[`README.md`] and push some apps!!

*MAKE SURE YOU CD INTO THE INDIVIDUAL APP DIRECTORIES*

== More talking

* Review the Keynote on link:Cloud_Ready_Apps.key[Cloud_Ready_Apps Ready Apps]
** This should drive home how to build applications that will run on PCF. As we'll cover PCF can work with lots of applications, but cloud native is the best fit. 

== More Exercises

* We're going to switch to a java application called `cities-service`. We will use this application for the remainder of the workshop. Find and download the cities jars at the following location. 

** https://s3-us-west-1.amazonaws.com/pcf-icm/cities-service.jar

** You can also find the code in this repository link:cities/[in dev-experience/cities]. We've made some changes to the code in the jar referenced above to force a failure early on. If you choose to compile and run the code yourself please remove the `hsqldb` dependency from the build file. Please note there is not time in the class to troubleshoot build issues, so if you experience problems please use the jar above. 

* Take a quick look at the link:cities/README.adoc[architecture] of the cities application. 

=== Applications on Pivotal CF

* Lets talk about about cloud ready apps and what cloud native means.
** :link:https://github.com/krujos/pcf-workshop/blob/pro/dev-experience/Cloud_Ready_Apps.key[Cloud Ready Apps]

* Review the documentation on link:http://docs.pivotal.io/pivotalcf/devguide/deploy-apps/prepare-to-deploy.html[Considerations for Designing and Running an Application in the Cloud]

* Review the documentation on link:http://docs.pivotal.io/pivotalcf/devguide/deploy-apps/streaming-logs.html#writing[Writing to logs]

* link:sdlc-basics.adoc[SDLC Basics]
** Pushing apps
** Using Manifests
** Dependency Injection in Spring
** Health, logging & events via the CLI
** Binding to services
** Environment variables
** Scaling apps

The following exercises should be completed for `cities-service`.

* link:user-console.adoc[User Console]

* link:app-log-drain.adoc[Application Log Draining]

* link:apm.adoc[Monitoring with APM tools]

* link:app-autoscaling.adoc[Application Autoscaling]
