= Developer Experience

== Goals

To deploy and configure an application, leverage the platform for monitoring & management of the microservices, and automate a continuous delivery pipeline.

== Exercises

=== Console

Before we do anything lets take a look at the developer console and confirm install of the Cloud Foundry CLI on our laptops/desktops. 

* link:http://docs.pivotal.io/pivotalcf/console/dev-console.html[User Console Docs]

* login to the console at https://console.run.pcf.jkruckcloud.com
* I am using a self signed cert, go through that little dance in your browser. 
* If you're using chrome, make sure it's a recent. Folks from THD have had some issues with an older version 
* Login with your THD email and a password of `password`
* Navigate to "Tools" (Left side)
* Download and install the CLI for your platform.
* Note theres some minimal instructions about what you'll do next given to you in the console. 

=== CLI
Now that we have the CLI, lets push some basic applications quickly and navigate our way around the CLI. 

* Login to Cloud Foundry

`cf login -a https://api.run.pcf.jkruckcloud.com -u <your email> -p password --skip-ssl-validation` 

. `-a` is the api we're targeting. Meaning all actions we perform will take place on this Cloud Foundry Foundation (deployment)

. `-u` is your username, in this workshop it's your email address.

. `-p` is your password. I've set it to password

=== Pushing apps
* Clone our example applications

`git clone https://github.com/krujos/cf-hello-world-sample-apps`

`cd cf-hello-world-sample-apps`

Read link:https://github.com/krujos/cf-hello-world-sample-apps/blob/master/README.md[`README.md`] and push some apps!!

== More talking

* Review the Keynote on link:Cloud_Ready_Apps.key[Cloud Ready Apps]
** This should drive home how to build applications that will run on PCF. As we'll cover PCF can work with lots of applications, but cloud native is the best fit. 

== More Exercises

* We're going to switch to a java application called `cities-service`. We will use this application for the remainder of the workshop. Find and download the cities jars at the following location. 

** https://s3-us-west-1.amazonaws.com/pcf-icm/cities-service.jar

=== Applications on Pivotal CF

* Review the documentation on link:http://docs.pivotal.io/pivotalcf/devguide/deploy-apps/prepare-to-deploy.html[Considerations for Designing and Running an Application in the Cloud]

* Review the documentation on link:http://docs.pivotal.io/pivotalcf/devguide/deploy-apps/streaming-logs.html#writing[Writing to logs]

* link:sdlc-basics.adoc[SDLC Basics]
** Pushing apps
** Using Manifests
** Dependency Injection in Spring
** Health, logging & events via the CLI
** Binding to services
** Environment variables
** Scaling apps

The following exercises should be completed for `cities-service`.

* link:user-console.adoc[User Console]

* link:app-log-drain.adoc[Application Log Draining]

* link:apm.adoc[Monitoring with APM tools]

* link:app-autoscaling.adoc[Application Autoscaling]

* link:../continuous-delivery/README.adoc[Continuous Delivery]
