= Service Brokers

== Goal

In this section, students will deploy a custom service broker.

. The haash-broker implements a HashMap as a Service

. Deploy the Service Broker as an app to Cloud Foundry

. Register the Broker with the Cloud Controller

. Make the single plan in the catalog “public”

. Create an instance of your service

. Push and bind a test app to your service instance

. Test the app’s interaction with the service


== Exercise

. Review the documentation on link:http://docs.pivotal.io/pivotalcf/services/[Creating Custom Services]

=== Overview

The Service Broker for this lab is for a service called HashMap as a Service (HaaSh). It wraps a minimal REST API around a Java HashMap implementation, and each service creation event results in a newly allocated Map.

Use the service-broker folder which has the haash-broker and haash-client.

=== haash-broker

* Edit the src/main/resources/import.sql file:
+
[source,bash]
----
insert into services (id, name, description, bindable) values ('<first-initial><last-initial>', '<first-initial><last-initial>-HaaSh', 'HaaSh - HashMap as a Service', true)
insert into plans (id, name, description, service_id) values ('<first-initial><last-initial>', 'basic', 'Basic Plan','<first-initial><last-initial>');
----
+

* Edit the haash-broker dashboard client code, add your initials to the String id field.
The DashboardClient class is in the src/main/java/io/pivotal/pcf/haash/model folder.
+
[source,bash]
----
public class DashboardClient {

	private final String id = "fooXX";
	private final String redirectURI = "http://example.com";
	private final String secret = "secret";
----

* Build the haash-broker, from the haash-broker folder.
+
[source,bash]
----
$ gradle assemble
----

* Push the broker as an app to CF.  Use the name: <first-initial><last-initial>-haash-broker

* Register the broker with the cloud controller:
+
[source,bash]
----
$ cf create-service-broker ...
----
+
The username & password you need for the broker are in: src/main/resources/application.properties

* Next, you need to make the plan public:
+
[source,bash]
----
$ cf enable-service-access ...
----
+
You will need to figure out the plan name.  You can do this by accessing your service broker's catalog from a browser.

* Verify you can see your new service in the marketplace.  There is a cf command for this.

* Create a new instance of your service using the CF commands.  Name the instance <first-initial><last-initial>-haash-service.

=== Haash Client

* Create a manifest for your haash-client.

* Be sure to connect the haash-client to the service instance you created above.

* Build the haash-client with gradle

* Push the haash-client to cf and name it: <first-initial><last-initial>-haash-client

* Curl your haash client to be sure it is working and using your haash-service
+
You can add key,value pairs using:
+
[source,bash]
----
$ curl <your haash-client>/HaaSh/<key> -d '<some value>' -X PUT
----
+

* You can retrieve the values:
+
[source,bash]
----
$ curl <your haash-client>/HaaSh/<key>
----
+


== Beyond the class

There are many community resources to help you build your own more robust service broker.

* Spring developers can use the link:https://github.com/cloudfoundry-community/spring-boot-cf-service-broker[Spring Boot CF Service Broker]

* You following repositories can be used as a reference:
** link:https://github.com/cloudfoundry-community/s3-cf-service-broker[S3 CF Service Broker]
** link:https://github.com/spgreenberg/spring-boot-cf-service-broker-mongo[Spring Boot CF Service Broker Mongo]
